# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['code/gui_app.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'customtkinter',
        'soundfile',
        'librosa',
        'soxr',
        'scipy',
        'numpy',
        'torchaudio',
        'torch',
        'PIL',
        'PIL._tkinter_finder',
        'packaging',
        'packaging.version',
        'packaging.specifiers',
        'code.utils',
        'code.config',
        'code.separation_engine',
        # Needed for torchaudio model downloads on fresh machines
        'huggingface_hub',
        'requests',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Remove heavy Jupyter/IPython bloat (not needed for this app)
        'IPython',
        'jedi',
        'parso',
        'zmq',
        'tornado',
        'prompt_toolkit',
        'wcwidth',
        'pyreadline3',
        'msgpack',
        'setuptools',
        # Remove test/unused modules
        'tkinter.test',
        'unittest',
        'test',
        'setuptools.tests',
        'pydoc',
        'http.server',
        'email.mime',
        'xml.etree',
        'xmlrpc',
        'asyncio.test',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    name='VocalPro',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='VocalPro',
)
